I know it's hard to dance, just be my copycat

diff --git a/bash_prompt b/bash_prompt
--- a/bash_prompt
+++ b/bash_prompt
@@ -1,257 +1,95 @@
-#!/usr/bin/env bash
-# Sexy bash prompt by twolfson
-# https://github.com/twolfson/sexy-bash-prompt
-# Forked from gf3, https://gist.github.com/gf3/306785
+####### Config #######
+PROMPT_ONELINE=1
 
-# If we are on a colored terminal
-if tput setaf 1 &> /dev/null; then
-  # Reset the shell from our `if` check
-  tput sgr0 &> /dev/null
+PROMPT_HOST=1
+HOST_COLOR="green"
 
-  # If you would like to customize your colors, use
-  # # Attribution: http://linuxtidbits.wordpress.com/2008/08/11/output-color-on-bash-scripts/
-  # for i in $(seq 0 $(tput colors)); do
-  #   echo " $(tput setaf $i)Text$(tput sgr0) $(tput bold)$(tput setaf $i)Text$(tput sgr0) $(tput sgr 0 1)$(tput setaf $i)Text$(tput sgr0)  \$(tput setaf $i)"
-  # done
+PROMPT_VIRTUALENV=1
+PROMPT_GITSTATUS=1
+PROMPT_JOBS=1
 
-  # Save common color actions
-  #prompt_bold="$(tput bold)" # tipishev: I don't need no bold
-  prompt_bold="$(tput sgr0)" # tipishev: I don't need no bold
-  prompt_reset="$(tput sgr0)"
+##### END config #####
 
-  # If the terminal supports at least 256 colors, write out our 256 color based set
-  if [[ "$(tput colors)" -ge 256 ]] &> /dev/null; then
-    prompt_user_color="$prompt_bold$(tput setaf 27)" # BOLD BLUE
-    prompt_preposition_color="$prompt_bold$(tput setaf 7)" # BOLD WHITE
-    prompt_device_color="$prompt_bold$(tput setaf 39)" # BOLD CYAN
-    prompt_dir_color="$prompt_bold$(tput setaf 76)" # BOLD GREEN
-    prompt_git_status_color="$prompt_bold$(tput setaf 154)" # BOLD YELLOW
-    prompt_git_progress_color="$prompt_bold$(tput setaf 9)" # BOLD RED
-  else
-  # Otherwise, use colors from our set of 8
-    prompt_user_color="$prompt_bold$(tput setaf 4)" # BOLD BLUE
-    prompt_preposition_color="$prompt_bold$(tput setaf 7)" # BOLD WHITE
-    prompt_device_color="$prompt_bold$(tput setaf 6)" # BOLD CYAN
-    prompt_dir_color="$prompt_bold$(tput setaf 2)" # BOLD GREEN
-    prompt_git_status_color="$prompt_bold$(tput setaf 3)" # BOLD YELLOW
-    prompt_git_progress_color="$prompt_bold$(tput setaf 1)" # BOLD RED
-  fi
+# imports
+GIT_STATUS_HELPER=~/dotfiles/sbp_git_status.sh
 
-  prompt_symbol_color="$prompt_bold" # BOLD
+# constants
+declare -A colors=(
+    ["black"]="\[\e[30;49m\]"
+    ["red"]="\[\e[31;49m\]"
+    ["green"]="\[\e[32;49m\]"
+    ["yellow"]="\[\e[33;49m\]"
+    ["blue"]="\[\e[34;49m\]"
+    ["magenta"]="\[\e[35;49m\]"
+    ["cyan"]="\[\e[36;49m\]"
+    ["white"]="\[\e[37;49m\]"
+    ["none"]="\[\e[0m\]"
+)
 
-else
-# Otherwise, use ANSI escape sequences for coloring
-  # If you would like to customize your colors, use
-  # DEV: 30-39 lines up 0-9 from `tput`
-  # for i in $(seq 0 109); do
-  #   echo -n -e "\033[1;${i}mText$(tput sgr0) "
-  #   echo "\033[1;${i}m"
-  # done
 
-  prompt_reset="\033[m"
-  prompt_user_color="\033[1;34m" # BLUE
-  prompt_preposition_color="\033[1;37m" # WHITE
-  prompt_device_color="\033[1;36m" # CYAN
-  prompt_dir_color="\033[1;32m" # GREEN
-  prompt_git_status_color="\033[1;33m" # YELLOW
-  prompt_git_progress_color="\033[1;31m" # RED
-  prompt_symbol_color="" # NORMAL
-fi
+# main
+function prompt_cmd_git {
+    [[ -x "$GIT_STATUS_HELPER" && $PROMPT_GITSTATUS -eq 1 ]] || exit 0
 
-# Apply any color overrides that have been set in the environment
-if [[ -n "$PROMPT_USER_COLOR" ]]; then prompt_user_color="$PROMPT_USER_COLOR"; fi
-if [[ -n "$PROMPT_PREPOSITION_COLOR" ]]; then prompt_preposition_color="$PROMPT_PREPOSITION_COLOR"; fi
-if [[ -n "$PROMPT_DEVICE_COLOR" ]]; then prompt_device_color="$PROMPT_DEVICE_COLOR"; fi
-if [[ -n "$PROMPT_DIR_COLOR" ]]; then prompt_dir_color="$PROMPT_DIR_COLOR"; fi
-if [[ -n "$PROMPT_GIT_STATUS_COLOR" ]]; then prompt_git_status_color="$PROMPT_GIT_STATUS_COLOR"; fi
-if [[ -n "$PROMPT_GIT_PROGRESS_COLOR" ]]; then prompt_git_progress_color="$PROMPT_GIT_PROGRESS_COLOR"; fi
-if [[ -n "$PROMPT_SYMBOL_COLOR" ]]; then prompt_symbol_color="$PROMPT_SYMBOL_COLOR"; fi
+    GIT_STATUS="$(${GIT_STATUS_HELPER})"
 
-function get_git_branch() {
-  # On branches, this will return the branch name
-  # On non-branches, (no branch)
-  ref="$(git symbolic-ref HEAD 2> /dev/null | sed -e 's/refs\/heads\///')"
-  if [[ "$ref" != "" ]]; then
-    echo "$ref"
-  else
-    echo "(no branch)"
-  fi
+    [[ -n "${GIT_STATUS}" ]] \
+    && echo "${colors[none]}:${GIT_STATUS}"
 }
 
-function get_git_progress() {
-  # Detect in-progress actions (e.g. merge, rebase)
-  # https://github.com/git/git/blob/v1.9-rc2/wt-status.c#L1199-L1241
-  git_dir="$(git rev-parse --git-dir)"
+function prompt_cmd_venv {
+    [[ $PROMPT_VIRTUALENV -eq 1 ]] || exit 0
 
-  # git merge
-  if [[ -f "$git_dir/MERGE_HEAD" ]]; then
-    echo " [merge]"
-  elif [[ -d "$git_dir/rebase-apply" ]]; then
-    # git am
-    if [[ -f "$git_dir/rebase-apply/applying" ]]; then
-      echo " [am]"
-    # git rebase
-    else
-      echo " [rebase]"
-    fi
-  elif [[ -d "$git_dir/rebase-merge" ]]; then
-    # git rebase --interactive/--merge
-    echo " [rebase]"
-  elif [[ -f "$git_dir/CHERRY_PICK_HEAD" ]]; then
-    # git cherry-pick
-    echo " [cherry-pick]"
-  fi
-  if [[ -f "$git_dir/BISECT_LOG" ]]; then
-    # git bisect
-    echo " [bisect]"
-  fi
-  if [[ -f "$git_dir/REVERT_HEAD" ]]; then
-    # git revert --no-commit
-    echo " [revert]"
-  fi
+    [[ -n "${VIRTUAL_ENV}" ]] \
+    && echo "${colors[none]}:${colors[blue]}${VIRTUAL_ENV##*/}${colors[none]}"
 }
 
-is_branch1_behind_branch2 () {
-  # $ git log origin/master..master -1
-  # commit 4a633f715caf26f6e9495198f89bba20f3402a32
-  # Author: Todd Wolfson <todd@twolfson.com>
-  # Date:   Sun Jul 7 22:12:17 2013 -0700
-  #
-  #     Unsynced commit
+function prompt_cmd_jobs {
+    [[ $PROMPT_JOBS -eq 1 ]] || exit 0
 
-  # Find the first log (if any) that is in branch1 but not branch2
-  first_log="$(git log $1..$2 -1 2> /dev/null)"
+    NUM_JOBS=$(jobs | wc -l)
+    [[ "$NUM_JOBS" -gt 0 ]] \
+    && echo "${colors[none]}:${colors[yellow]}&${colors[none]}"
+    # && echo "${colors[none]}:${colors[yellow]}&${NUM_JOBS}${colors[none]}"
 
-  # Exit with 0 if there is a first log, 1 if there is not
-  [[ -n "$first_log" ]]
 }
 
-branch_exists () {
-  # List remote branches           | # Find our branch and exit with 0 or 1 if found/not found
-  git branch --remote 2> /dev/null | grep --quiet "$1"
+function prompt_cmd {
+    # Cursor color is determined by the exit status of the last command.
+    [[ "$?" -eq 0 ]] \
+    && CLR_CURSOR="${colors[green]}" \
+    || CLR_CURSOR="${colors[red]}"
+
+    # User color is determined by the current UID, root=red
+    [[ "${UID}" -eq 0 ]] \
+    && CLR_USER="${colors[red]}" \
+    || CLR_USER="${colors[green]}"
+
+    [[ "${PROMPT_HOST}" -eq 1 ]] \
+    && STATUS_HOST="${colors[none]}@${colors[${HOST_COLOR}]}\h" \
+    || STATUS_HOST=""
+
+    STATUS_VENV="$(prompt_cmd_venv)"
+    STATUS_GIT="$(prompt_cmd_git)"
+    STATUS_JOBS="$(prompt_cmd_jobs)"
+
+    [[ "PROMPT_ONELINE" -eq 1 ]] \
+    && SEPARATOR=' ' \
+    || SEPARATOR='\n'
+
+    PS1="\
+${TITLEBAR}\
+${CLR_USER}\u\
+${STATUS_HOST}\
+${STATUS_VENV}\
+${STATUS_GIT}\
+${colors[none]}:\
+${colors[none]}\w\
+${STATUS_JOBS}\
+${SEPARATOR}\
+${CLR_CURSOR}\\$ \
+${colors[none]}\
+"
 }
 
-parse_git_ahead () {
-  # Grab the local and remote branch
-  branch="$(get_git_branch)"
-  remote_branch="origin/$branch"
-
-  # $ git log origin/master..master
-  # commit 4a633f715caf26f6e9495198f89bba20f3402a32
-  # Author: Todd Wolfson <todd@twolfson.com>
-  # Date:   Sun Jul 7 22:12:17 2013 -0700
-  #
-  #     Unsynced commit
-
-  # If the remote branch is behind the local branch
-  # or it has not been merged into origin (remote branch doesn't exist)
-  if (is_branch1_behind_branch2 "$remote_branch" "$branch" ||
-      ! branch_exists "$remote_branch"); then
-    # echo our character
-    echo 1
-  fi
-}
-
-parse_git_behind () {
-  # Grab the branch
-  branch="$(get_git_branch)"
-  remote_branch="origin/$branch"
-
-  # $ git log master..origin/master
-  # commit 4a633f715caf26f6e9495198f89bba20f3402a32
-  # Author: Todd Wolfson <todd@twolfson.com>
-  # Date:   Sun Jul 7 22:12:17 2013 -0700
-  #
-  #     Unsynced commit
-
-  # If the local branch is behind the remote branch
-  if is_branch1_behind_branch2 "$branch" "$remote_branch"; then
-    # echo our character
-    echo 1
-  fi
-}
-
-function parse_git_dirty() {
-  # If the git status has *any* changes (e.g. dirty), echo our character
-  if [[ -n "$(git status --porcelain 2> /dev/null)" ]]; then
-    echo 1
-  fi
-}
-
-function is_on_git() {
-  git rev-parse 2> /dev/null
-}
-
-function get_git_status() {
-  # Grab the git dirty and git behind
-  dirty_branch="$(parse_git_dirty)"
-  branch_ahead="$(parse_git_ahead)"
-  branch_behind="$(parse_git_behind)"
-
-  # Iterate through all the cases and if it matches, then echo
-  if [[ "$dirty_branch" == 1 && "$branch_ahead" == 1 && "$branch_behind" == 1 ]]; then
-    echo "⬢"
-  elif [[ "$dirty_branch" == 1 && "$branch_ahead" == 1 ]]; then
-    echo "▲"
-  elif [[ "$dirty_branch" == 1 && "$branch_behind" == 1 ]]; then
-    echo "▼"
-  elif [[ "$branch_ahead" == 1 && "$branch_behind" == 1 ]]; then
-    echo "⬡"
-  elif [[ "$branch_ahead" == 1 ]]; then
-    echo "△"
-  elif [[ "$branch_behind" == 1 ]]; then
-    echo "▽"
-  elif [[ "$dirty_branch" == 1 ]]; then
-    echo "*"
-  fi
-}
-
-get_git_info () {
-  # Grab the branch
-  branch="$(get_git_branch)"
-
-  # If there are any branches
-  if [[ "$branch" != "" ]]; then
-    # Echo the branch
-    output="$branch"
-
-    # Add on the git status
-    output="$output$(get_git_status)"
-
-    # Echo our output
-    echo "$output"
-  fi
-}
-
-# Symbol displayed at the line of every prompt
-function get_prompt_symbol() {
-  # If we are root, display `#`. Otherwise, `$`
-  if [[ "$UID" == 0 ]]; then
-    echo "#"
-  else
-    echo "\$"
-  fi
-}
-
-# backup
-# Define the sexy-bash-prompt
-#PS1="\[$prompt_user_color\]\u\[$prompt_reset\] \
-#\[$prompt_preposition_color\]at\[$prompt_reset\] \
-#\[$prompt_device_color\]\h\[$prompt_reset\] \
-#\[$prompt_preposition_color\]in\[$prompt_reset\] \
-#\[$prompt_dir_color\]\w\[$prompt_reset\]\
-#\$( is_on_git && \
-#  echo -n \" \[$prompt_preposition_color\]on\[$prompt_reset\] \" && \
-#  echo -n \"\[$prompt_git_status_color\]\$(get_git_info)\" && \
-#  echo -n \"\[$prompt_git_progress_color\]\$(get_git_progress)\" && \
-#  echo -n \"\[$prompt_preposition_color\]\")\n\[$prompt_reset\]\
-#\[$prompt_symbol_color\]$(get_prompt_symbol) \[$prompt_reset\]"
-
-# Define the sexy-bash-prompt
-PS1="\[$prompt_reset\]\[$prompt_dir_color\]\w\[$prompt_reset\]\
-\$( is_on_git && \
-  echo -n \" \[$prompt_preposition_color\]on\[$prompt_reset\] \" && \
-  echo -n \"\[$prompt_git_status_color\]\$(get_git_info)\" && \
-  echo -n \"\[$prompt_git_progress_color\]\$(get_git_progress)\" && \
-  echo -n \"\[$prompt_preposition_color\]\")\[$prompt_reset\]\
-\[$prompt_symbol_color\]$(get_prompt_symbol) \[$prompt_reset\]"
+PROMPT_COMMAND=prompt_cmd
